Create Profile Picture
UofTCCF/RuntogetherCCF pull request #31
Opened 2022-07-08 22:35 UTC by kelvincklo

## Changes

> Created profilePicture component. Also created Components folder.

## Checklist

- [x] Pull request has descriptive context useful to reviewer. Screenshots are attached as necessary.
- [x] Pull request title matches Linear ticket.
- [x] Ticket has been claimed on Linear
- [x] Pull Request has been assigned to yourself
- [ ] Pull request has been approved by CodeOwner
- [ ] Pull request has been approved by one other student

2022-07-09 00:57 UTC, NeoLou requested changes
I think you should try to test it first to see if it works as intended by importing it into App.js and seeing if it renders when you start the app.

2022-07-10 03:45 UTC, kelvincklo commented
> I think you should try to test it first to see if it works as intended by importing it into App.js and seeing if it renders when you start the app.

Ty for the comment Neo, I've imported the ProfilePicture component and tested it in App.js.

2022-07-11 01:08 UTC, Jnwong116 approved these changes

2022-07-11 01:19 UTC, NeoLou approved these changes
LGTM!

2022-07-11 01:19 UTC, Jnwong116 commented on client/src/component/profilePicture/profilePicture.js
> +    return <img class="profile-pic" src={img_link} />;
Might need to change how we load up the src depending on where we get the images from. 

`src={require("../../assets/images/" + this.props.icon)}`

2022-07-11 01:47 UTC, merged